### ISSUE TITLE
Funding source for configurations and setups is missing

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries#14]
[`/getModelConfigurationMetadata`](https://github.com/mintproject/MINT-ModelCatalogQueries/blob/master/getModelConfigurationMetadata.rq) has `?fundS` but its returning nothing.

I checked on the sparql endpoint with this query:
```
SELECT * WHERE {
  GRAPH mcd:mint {
	?x sd:fundingSource ?fundS ;
	   a ?type. 
    VALUES ?type {sdm:ModelConfiguration sdm:ModelConfiguration}
  }
}
```
but its returning nothing, so i think maybe this information does not exists.
This issue is related to https://github.com/mintproject/mint-ui-lit/issues/72

**Comment by dgarijo** [comment]
It's returning nothing because this info is not available yet. I will close the issue.
