### ISSUE TITLE
Return data types

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries#2]
Whenever an input or output is returned (a DatasetSpecification), we should return its datatypes, filtering out DatasetSpecification

**Comment by ddanuj** [comment]
@dgarijo Please check latest commits - [1](https://github.com/KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries/commit/242f7911187ab852bf105f39cbfbc0c5def99eed) and [2](https://github.com/KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries/commit/94468992e2a50f3a5a30b1df46b412383b52797c)
