### ISSUE TITLE
Get executable information for model configuration

### ISSUE THREAD

**Issue by dhruvp-8** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries#3]
@ddanuj Can you provide an API endpoint to display executable info for configuration?

**Comment by ddanuj** [comment]
@dhruvp-8 what do you mean by executable info ? @dgarijo The model configuration has input, output, processes and other meta data. Which of these is expected here ?

**Comment by dgarijo** [comment]
For the moment the value of:
https://w3id.org/mint/modelCatalog#hasComponentLocation

**Comment by ddanuj** [comment]
@dgarijo @dhruvp-8 Please check [latest commit](https://github.com/KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries/commit/1f15c254ec82cba7f2a7341e2e36a7b4dc081786)

**Comment by ddanuj** [comment]
Returning Component Location for Configuration whenever available.
