### ISSUE TITLE
Version label mismatch for cycles

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/MINT-ModelCatalogQueries#8]
For cycles 0.9.4 the uri of configurations and calibrations are using `cycles-v2` as prefix, also IO and params are using `_v2` as shows here
![Screen Shot 2019-09-11 at 12 16 18](https://user-images.githubusercontent.com/15269912/64710611-a9292000-d48e-11e9-8f2e-3cd783a163a1.png)

It's intentional?

**Comment by dgarijo** [comment]
Yes, because it was the second version of the component in wings. Since the
uri is not shown, it's fine.

**Comment by hvarg** [comment]
Ok thanks!, im closing this issue.
